### ISSUE TITLE
Run SLAM on multiple DS80 at the same time

### ISSUE THREAD

**Issue by nobuyukimatsuno** [robodreamer/xvisiotech_camera_examples#4]
Related issue to https://github.com/robodreamer/xvisiotech_camera_examples/issues/3

I'm using this ros driver on ubuntu 22.04/humble. After launching two DS80s at the same time, I can see camera image messages from both devices. However, once they initialize and start SLAM, the poses of the devices move randomly near initial positions, and then in a few seconds, the driver dies with `Segmentation fault`. If I test with only one device, SLAM works fine. GDB says the error coming from this:
```
0x00007ffff5afe447 in bool IncrementalTracker<640, 400, (IncrementalTrackerSIMD::SimdSet)0>::extractPatch<0>(unsigned char const*, float*, std::array<Eigen::Matrix<float, 2, 1, 0, 2, 1>, 4ul> const&) const () from /lib/libxvslam.so
```
I guess this error is not in this ros driver, but the SDK itself, but if you know something about it, I'd like to know.

Thank you.

**Comment by robodreamer** [comment]
I see. I just relayed this to the dev team as well, and will let you know as soon as I hear back from them. Thanks for the patience! BTW, so glad to hear that the previous issue was resolved with the fix the dev team suggested! 😄

**Comment by nobuyukimatsuno** [comment]
Thank you so much!!

**Comment by robodreamer** [comment]
You are welcome! @nobuyukimatsuno the dev team is still looking into the issue atm, but in the meantime, I would recommend you to try out the updated dev branch. I tested a newer driver I got from dev team and made some other QoL improvements in general. I still have some issues that I will report back to them, but it seems better in general. Let me know if you still get the same error with the latest `dev` branch or not.

**Comment by nobuyukimatsuno** [comment]
Thank you for the update! I tested the latest `dev` and driver, but unfortunately I still have the same issue when running SLAM on two devices.
